# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'NFS | Configure exports directories.'
  become: yes
  file:
    path: '{{ item.path }}'
    state: 'directory'
    owner: '{{ item.owner | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '{{ item.mode | default("0755") }}'
  notify: 'restart nfs'
  with_items: '{{ nfs_exports }}'
  when: 'nfs_exports | default(None) != None'

- name: 'NFS | Configure exports file.'
  become: yes
  template:
    src: '{{ nfs_exports_template }}'
    dest: '/etc/exports'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart nfs'

- name: 'NFS | Configure mounts.'
  become: yes
  mount:
    name: '{{ item.name }}'
    dump: '{{ item.dump | default(omit) }}'
    fstab: '{{ item.fstab | default(omit) }}'
    fstype: '{{ item.fstype | default(omit) }}'
    opts: '{{ item.opts | default(omit) }}'
    passno: '{{ item.passno | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    state: '{{ item.state | default("mounted") }}'
  with_items: '{{ nfs_mounts }}'
  when: 'nfs_mounts | default(None) != None'