# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'restart nfs'
  become: yes
  service:
    name: '{{ nfs_service_name }}'
    state: 'restarted'
  when: 'nfs_service_enabled'

- name: 'reload exports'
  become: yes
  command: 'exportfs -ra'
  when: 'nfs_service_enabled'